require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Performance:
  Exclude:
    - '**/test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
