module SnippetsHelper
  LANGUAGE_MODES = {
    'dart': 'application/dart',
    'javascript': 'application/javascript',
    'clojure': 'text/x-clojure',
    'json': 'application/x-json',
    'typescript': 'text/typescript',
    'coffeescript': 'text/coffeescript',
    'php': 'application/x-httpd-php',
    'shell': 'text/x-sh',
    'xml': 'application/xml',
    'css': 'text/css',
    'markdown': 'text/markdown',
    'text': 'text/plain',
    'rust': 'text/rust',
    'c': 'text/x-c',
    'commonlisp': 'text/x-common-lisp',
    'crystal': 'text/x-crystal',
    'python': 'text/x-python',
    'diff': 'text/x-diff',
    'dockerfile': 'text/x-dockerfile',
    'erlang': 'text/x-erlang',
    'sql': 'text/x-sql',
    'go': 'text/x-go',
    'groovy': 'text/x-groovy',
    'java': 'text/x-java',
    'protobuf': 'text/x-protobuf',
    'r': 'text/x-rsrc',
    'swift': 'text/x-swift',
    'yaml': 'text/yaml',
  }
end
